# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


jobs:
  - job: "linux_binary"
    displayName: 'Build Linux binary'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo Installing packages.
        sudo apt-get install git build-essential libx11-dev cmake \
        make libxrandr-dev mesa-common-dev libglu1-mesa-dev \
        libudev-dev libglew-dev libjpeg-dev libfreetype6-dev \
        libopenal-dev libsndfile1-dev libxcb1-dev \
        libxcb-image0-dev cmake gcc g++ zip unzip
        sudo apt-get install libsfml-dev
      displayName: 'Preparing environment'
    - script: |
        git clone https://github.com/daid/EmptyEpsilon.git
        git clone https://github.com/daid/SeriousProton.git
        cd EmptyEpsilon
        mkdir -p _build
      displayName: 'Preparing directory structure'
    - script: |
        cd EmptyEpsilon/_build
        cmake .. -DSERIOUS_PROTON_DIR=$PWD/../../SeriousProton/
        make
        cpack -G DEB -R $(git rev-parse HEAD)
      displayName: 'Building deb package'
